### ISSUE TITLE
Error when trying to install Genegos

### ISSUE THREAD

**Issue by ivargr** [liu-yongji/genegos#1]
Hi!

I am trying to install Genegos, but get a compile error when running `make`.

This is what I have done:
1) Clone this repository
2) Extracted `genegos-1.0.0.tar.gz`
3) Run `./configure`
4) Run `make`

This then fails with the following error message:

```
genegos.cpp:1517:36: error: call of overloaded ‘to_string(int)’ is ambiguous
```

I am on Ubuntu 20.04 using GNU Make version  4.2.1 and gcc version 9.3.0.

**Comment by liu-yongji** [comment]
hi:
I'm sorry to reply you so late.
This problem is caused by different compiler versions and I have fixed it.
Please re-download and install the compressed package again.
Thanks for your attention.

________________________________
发件人: ivargr <notifications@github.com>
发送时间: 2020年10月10日 3:05
收件人: liu-yongji/genegos <genegos@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [liu-yongji/genegos] Error when trying to install Genegos (#1)


Hi!

I am trying to install Genegos, but get a compile error when running make.

This is what I have done:

  1.  Clone this repository
  2.  Extracted genegos-1.0.0.tar.gz
  3.  Run ./configure
  4.  Run make

This then fails with the following error message:

genegos.cpp:1517:36: error: call of overloaded ‘to_string(int)’ is ambiguous



I am on Ubuntu 20.04 using GNU Make version 4.2.1 and gcc version 9.3.0.

―
